- storage-access.bs
This change updates the spec with a WebDriver extension command for modifying the user agent's storage access policy. This is to address: https://github.com/w3c/webdriver/issues/1437#issue-474647752
> Add Automation subsection

- storage-access.bs
> Use the same task queue as the Permissions API.

- storage-access.bs
> Direct-child check: use "parent browsing context", not "opener browsing context".

- storage-access.bs
This includes another commit because it is based on #68
Fixes #50, #69
This is based on some of Anne's feedback around how we run async steps
in parallel and queue tasks for resolving promises instead of what we
were doing before.
This also moves a bunch of things that probably don't need to happen
in parallel (and don't happen in parallel in at least Gecko and WebKit)
out of the async steps.
> Fix async steps in hasStorageAccess and requestStorageAccess.

- storage-access.bs
> Disallow storage access when the top-level origin is an opaque origin.

- storage-access.bs
This is a first stab at integrating permissions policy and support nested iframes in the spec, see #10 and #12 . A few notes:
* I'm happy to bikeshed on the permission name (`"request-storage-access"`). It's important to note that this policy only controls *requesting* storage access, it does not tell user agents with persistent/passive storage (see #2) how to behave if an `allow=none` attribute was added after an iframe received storage access.
* We're now using the `"*"` default allowlist which @annevk [intended to deprecate](https://github.com/w3c/webappsec-permissions-policy/issues/381). We went back and fort on this but ultimately `"*"` captures the reality of current implementations best, especially considering that WebKit does not have PP support (and thus implictly default to …
> Permissions Policy Integration (formalize nested iframe support)

- storage-access.bs
This was discussed before in #12 and there was some valid concern around
the "storage-access" name based on the fact that this PP feature is more
focused on "requesting" storage access, and there is no delegation
mechanism like with other permissions that would make it semantically
consistent.
However, I think that in light of #32 and the possibility of integrating
with the permissions API (giving us important functionality such as
observing when storage access is granted) it seems more useful to be
consistent with the (future) permission name and call both "storage-access".
***
<a href="https://pr-preview.s3.amazonaws.com/johannhof/storage-access/pull/105.html" title="Last updated on Jul 18, 2022, 6:33 PM UTC (d1d54fc)">Preview</a> | <a …
> Change permissions policy feature name to "storage-access" (fixes #104)

- storage-access.bs
Please see discussion in https://crbug.com/1354256 for context.
The particular case that started this discussion was behavior in
detached frames.
The wording was largely pulled from:
https://github.com/whatwg/webidl/blob/main/index.bs#L8510-L8511
***
<a href="https://pr-preview.s3.amazonaws.com/mreichhoff/storage-access/pull/108.html" title="Last updated on Aug 18, 2022, 9:35 PM UTC (c187ddb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/privacycg/storage-access/108/104dbe5...mreichhoff:c187ddb.html" title="Last updated on Aug 18, 2022, 9:35 PM UTC (c187ddb)">Diff</a>
> Specify behavior for non-fully active documents

- storage-access.bs
@mreichhoff I noticed that InvalidStateError seems to be the most common error state for non-fully active checks, is there any particular reason we picked a SecurityError in Chromium for this?
***
<a href="https://pr-preview.s3.amazonaws.com/johannhof/storage-access/pull/112.html" title="Last updated on Sep 2, 2022, 11:42 AM UTC (a1a1a41)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/privacycg/storage-access/112/7e9c01f...johannhof:a1a1a41.html" title="Last updated on Sep 2, 2022, 11:42 AM UTC (a1a1a41)">Diff</a>
> Use InvalidStateError instead of SecurityError for fully active checks

- storage-access.bs
I am both rejecting with a "{{NotAllowedError}}" {{DomException}} in all contexts where we reject undefined and no longer rejecting where we don't want to leak user choice timing. (#60 and #37)
***
<a href="https://pr-preview.s3.amazonaws.com/bvandersloot-mozilla/storage-access/pull/118.html" title="Last updated on Sep 29, 2022, 2:31 AM UTC (e7a2087)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/privacycg/storage-access/118/d9d8f41...bvandersloot-mozilla:e7a2087.html" title="Last updated on Sep 29, 2022, 2:31 AM UTC (e7a2087)">Diff</a>
> Reject with DomException or never reject 

- storage-access.bs
This PR restricts usage of the API to within a secure context, and closes https://github.com/privacycg/storage-access/issues/125. As the Storage Access API is intended to address authenticated embeds while protecting user privacy, this change is not expected to be controversial.
* Chrome
* Firefox
* https://crrev.com/c/3991336
* Chromium: https://crbug.com/1380155
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1798407
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=247286
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://pr-preview.s3.amazonaws.com/cfredric/storage-access/pull/132.html" title="Last updated on Oct 31, 2022, 9:22 PM UTC (24883f6)">Preview</a> | <a …
> Restrict usage to within a secure context.

- storage-access.bs
* Mozilla
* Chrome
* …
* Chromium: …
* Gecko: …
* WebKit: …
This should resolve #134.
TODO before merge:
***
<a href="https://pr-preview.s3.amazonaws.com/bvandersloot-mozilla/storage-access/pull/135.html" title="Last updated on Oct 25, 2022, 3:07 PM UTC (5da8406)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/privacycg/storage-access/135/c7abefa...bvandersloot-mozilla:5da8406.html" title="Last updated on Oct 25, 2022, 3:07 PM UTC (5da8406)">Diff</a>
> Reorder state checks to be consistent between requestStorageAccess and hasStorageAccess

- storage-access.bs
A large change to HTML landed and I am more willing to have broken links than a non-updating spec for now.
* Mozilla
* 
* N/A
* N/A
***
<a href="https://pr-preview.s3.amazonaws.com/bvandersloot-mozilla/storage-access/pull/136.html" title="Last updated on Nov 16, 2022, 12:56 PM UTC (a4b5337)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/privacycg/storage-access/136/9e4f9dc...bvandersloot-mozilla:a4b5337.html" title="Last updated on Nov 16, 2022, 12:56 PM UTC (a4b5337)">Diff</a>
> Remove fail on warning from build

- storage-access.bs
Editorial change, deleting the PR template...
Hopefully this represents a good first draft. Aiming to resolve #115.
***
<a href="https://pr-preview.s3.amazonaws.com/bvandersloot-mozilla/storage-access/pull/142.html" title="Last updated on Dec 14, 2022, 2:30 PM UTC (a4ad823)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/privacycg/storage-access/142/7908c22...bvandersloot-mozilla:a4ad823.html" title="Last updated on Dec 14, 2022, 2:30 PM UTC (a4ad823)">Diff</a>
>  Add Privacy and Security Considerations

- storage-access.bs
This is a bit hand-wavy but approximately what we discussed should live in this section at TPAC.
***
<a href="https://pr-preview.s3.amazonaws.com/johannhof/storage-access/pull/145.html" title="Last updated on Jan 5, 2023, 12:08 PM UTC (edff530)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/privacycg/storage-access/145/7908c22...johannhof:edff530.html" title="Last updated on Jan 5, 2023, 12:08 PM UTC (edff530)">Diff</a>
> Add preliminary description of how we integrate with cookies

- storage-access.bs
This is building on top of https://github.com/w3c/permissions/pull/390 to integrate SAA with permissions. It's deleting a lot of old manual state management but doesn't get rid of the (global) storage access map altogether, since that is done in the per-frame change being worked on by @cfredric.
This is a bit WIP just by virtue of the other change not having merged yet. I removed some of the references to the other spec to avoid the build from breaking.
* This is already tested as much as possible through using `test_driver.set_permission` in tests. We could follow up with tests that confirm that the `storage-access` feature is exposed via permissions APIs but that may need a separate spec change.
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1401266
* Gecko: …
> Use the Permissions API (closes #121, #32)

- storage-access.bs
This is an attempt to migrate to a "per-frame" model, as discussed in https://github.com/privacycg/storage-access/issues/122. This is built on top of #138 as a starting point.
The approach is to define a flag that lives on environment, and is set by `document.requestStorageAccess` and read by `document.hasStorageAccess`. In order to propagate storage access during self-initiated, same-origin navigations, we also add a flag to the `source snapshot params` used during `create navigation params by fetching`, and conditionally copy the `sourceDocument`'s relevant settings object's flag over to the new environment that will be created. This should let us achieve the benefits of the BrowsingContext approach discussed in #122, without having to add and clear state in BrowsingContext.
Leaving the …
> Modify Storage Access to use a "per-frame" model

- storage-access.bs
(closes #156)
This was originally part of #159 but I'm submitting it separately since this is a rather editorial change that we can probably fast-track without including it in the other PR which still needs WPT etc.
***
<a href="https://pr-preview.s3.amazonaws.com/johannhof/storage-access/pull/161.html" title="Last updated on Jan 26, 2023, 5:26 PM UTC (a86a871)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/privacycg/storage-access/161/ab80b38...johannhof:a86a871.html" title="Last updated on Jan 26, 2023, 5:26 PM UTC (a86a871)">Diff</a>
> Editorial: Remove partitioned storage key and implementation-defined steps

- storage-access.bs
This updates the permission key for storage-access to (site, site), and also removes the concept of the "partitioned storage key", which was origin-keyed as well. The storage key was only used for running the implementation-defined steps that are supposed to be removed as of #156.
* https://chromium-review.googlesource.com/c/chromium/src/+/4307251
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1418470
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1825216
* WebKit: Shipping behavior
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://pr-preview.s3.amazonaws.com/johannhof/storage-access/pull/159.html" title="Last updated on Mar 29, 2023, 8:35 AM UTC (52a6cc2)">Preview</a> | <a …
> Switch to (top-level site, embedded site) keying (closes #147, #156)

- storage-access.bs
This commit tries to make rSA and hSA match the reality of cookie blocking browsers perform in edge cases such as A > A and A > B > A. I think all browsers perform a same site check, so moving away from same origin makes sense. Additionally, Chrome will block cookies based on the "site for cookies" whereas Firefox and Safari don't. We plan to discuss this behavior separately and can hopefully align eventually.
As discussed with the other editors, we agree that it still makes sense from a privacy perspective to automatically grant storage access in a same site scenario, since the "site for cookies" check is for security only. This could previously lead to inconsistencies in browsers that block cookies based on "site for cookies", as hSA would return true and rSA would resolve automatically …
> Specify behavior in A > * > A scenarios

- storage-access.bs
This commits tries to make hSA match the description in the spec that “This specification defines a method to query whether or not a [Document](https://dom.spec.whatwg.org/#document) currently has access to its [unpartitioned data](https://privacycg.github.io/storage-access/#unpartitioned-data) ([hasStorageAccess()](https://privacycg.github.io/storage-access/#dom-document-hasstorageaccess)) …” by including a check of whether the user agent allows the `document` to access unpartitioned data based on user settings.
* https://chromium-review.googlesource.com/c/chromium/src/+/4611289
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1433013
* Gecko: N/A
* WebKit: N/A
Fixes https://github.com/privacycg/storage-access/issues/171
(See [WHATWG Working Mode: …
> Let `document.hasStorageAccess` check whether the Document already has unpartitioned data access

- README.md
This updates Chrome's position to indicate that we are shipping our implementation. Chrome's implementation is now enabled on desktop platforms in Chrome; Android is not far behind.
> Update Chrome's implementation status to "shipping"

- storage-access.bs
This change tries to make rSA behavior aligns with hSA and user expectations by including a check of whether the user agent allows the `document` to access unpartitioned data based on user settings, and move early resolve cases, such as top-level case and same-site case, behind the user settings check. Specifically:
* For the cases where hSA returns true, calling rSA will not show a prompt.
* For the cases where hSA returns false, calling rSA may or may not show a prompt:
* If user settings explicitly disallow unpartitioned data access, calling rSA will resolve with "denied" and not show a prompt.
* If no user settings exist, calling rSA may either resolve with "granted" depending on heuristics and not show a prompt, or show a prompt when there isn't an existing grant.
* …
* …
* …
* …
> document.requestStorageAccess should consider user explicit settings for unpartitioned data access

- storage-access.bs
The Chromium implementation was updated in https://crrev.com/c/5503610 and https://crrev.com/c/5503661.
***
<a href="https://pr-preview.s3.amazonaws.com/cfredric/storage-access/pull/207.html" title="Last updated on Oct 17, 2024, 8:28 PM UTC (29dd85b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/privacycg/storage-access/207/e239ed6...cfredric:29dd85b.html" title="Last updated on Oct 17, 2024, 8:28 PM UTC (29dd85b)">Diff</a>
> Update Chromium's implementation location in comment

- storage-access.bs
This splits out the underlying infrastructure changes introduced in #213 so that #213 can just introduce the behavior change, and this PR can add the infrastructure needed to formally define the current behavior (in Chrome and Firefox; Safari TBD).
I also incorporated @annevk's request that `request/eligible for storage-access` be a tri-state enum, rather than a boolean.
This PR relies on the `environment/ancestry` enum, similar to other cookie layering work ([e.g.](https://github.com/whatwg/fetch/pull/1807)).
* Chrome
* …
* https://crrev.com/c/6330426
* Chromium: https://crbug.com/379030052
* Gecko: …
* WebKit: …
***
<a href="https://pr-preview.s3.amazonaws.com/cfredric/storage-access/pull/214.html" title="Last updated on Mar 21, 2025, 3:35 PM UTC (1727745)">Preview</a> | <a …
> Introduce `request` infrastructure for storage access

- storage-access.bs
This is meant to address the ambiguities pointed out in #210 by defining Storage Access's integration with Fetch more rigorously. This PR codifies the behavior I'd like to Storage Access implementations to align on (namely stricter adherence to the Same Origin Policy).
* Chrome
* Webkit
* Firefox
* https://crrev.com/c/6241903 ([wpt.fyi](https://wpt.fyi/results/storage-access-api/requestStorageAccess-cross-origin-fetch.sub.https.tentative.window.html))
* Chromium: https://crbug.com/379030052
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1960071
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=291440
***
<a href="https://pr-preview.s3.amazonaws.com/cfredric/storage-access/pull/213.html" title="Last updated on Apr 11, 2025, 7:27 PM UTC (1938b57)">Preview</a> | <a …
> Adhere to Same Origin Policy more strictly
